def for1():
    print("(a+b)^2 = (a * a) + (b * b) + (2 * a * b)")
    c0 = (a * a)
    print("a*a =", c0)
    c1 = (b * b)
    print("b*b =", c1)
    c2 = (2 * a * b)
    print("2*a*b =", c2)
    x = c0 + c1 + c2
    print(c0, "+", c1, "+", c2, "=", x)
    print("total =", x)
def for2():
    print("(a+b)^2 = (a * a) + (b * b) - (2 * a * b)")
    c0 = (a * a)
    print("a*a =", c0)
    c1 = (b * b)
    print("b*b =", c1)
    c2 = (2 * a * b)
    print("2*a*b =", c2)
    x = c0 + c1 - c2
    print(c0, "+", c1, "-", c2, "=", x)
    print("total =", x)
def for3():
    print("(a+b)^3 = (a)^3+(b)^3+[3*(a)^2*b]+[3*a*(b)^2]")
    c0 = (a * a * a)
    print("a*a*a =", c0)
    c1 = (b * b * b)
    print("b*b*b =", c1)
    c2 = (3 * (a * a) * b)
    print("3*(a*a)*b =", c2)
    c3 = (3 * (b * b) * a)
    print("3*a*(b*b) =", c3)
    x = c0 + c1 + c2 + c3
    print(c0, "+", c1, "+", c2, "+", c3, "=",x)
    print("total =", x)
def for4():
    print("(a-b)^3 = (a)^3-(b)^3-[3*(a)^2*b]+[3*a*(b)^2]")
    c0 = (a * a * a)
    print("a*a*a =", c0)
    c1 = (b * b * b)
    print("b*b*b =", c1)
    c2 = (3 * (a * a) * b)
    print("3*(a*a)*b =", c2)
    c3 = (3 * (b * b) * a)
    print("3*a*(b*b) =", c3)
    x = c0 - c1 - c2 + c3
    print(c0, "-", c1, "-", c2, "+", c3, "=", x)
    print("total =", x)
def for5():
    print("(a)^3+(b)^3 = (a + a) ((a * a) - (b * b) + (2 * a * b)")
    c0 = (a + a)
    print("a+b =", c0)
    c1 = (a * a)
    print("a*a =", c1)
    c2 = (b * b)
    print("b*b =", c2)
    c3 = (2 * a * b)
    print("2*a*b =", c3)
    x = c0 * (c1 - c2 + c3)
    print(c0, "*", c1, "-", c2, "+", c3, "=", x)
    print("total =", x)
def for6():
    print("(a)^3+(b)^3 = (a - a) ((a * a) + (b * b) + (2 * a * b)")
    c0 = (a - a)
    print("a-b =", c0)
    c1 = (a * a)
    print("a*a =", c1)
    c2 = (b * b)
    print("b*b =", c2)
    c3 = (2 * a * b)
    print("2*a*b =", c3)
    x = c0 * (c1 - c2 + c3)
    print(c0, "*", c1, "+", c2, "+", c3, "=", x)
    print("total =", x)
def for7():
    print("(a+b+c)^2 = (a)^2+(b)^2+(c)^2+2ab+2bc+2ca")
    c0 = (a * a)
    print("a * a =", c0)
    c1 = (b * b)
    print("b * b =", c1)
    c2 = (c * c)
    print("c * c =", c2)
    c3 = (2 * a * b)
    print("2 * a * b =", c3)
    c4 = (2 * b * c)
    print("2 * b * c =", c4)
    c5 = (2 * c * a)
    print("2 * c * a =", c5)
    x = c0 + c1 + c2 + c3 + c4 + c5
    print(c0, "+", c1, "+", c2, "+", c3, "+", c4, "+", c5, "=", x)
    print("total =", x)
def for8():
    print("(a-b-c)^2 = (a)^2+(b)^2+(c)^2-2ab+2bc-2ca")
    c0 = (a * a)
    print("a * a =", c0)
    c1 = (b * b)
    print("b * b =", c1)
    c2 = (c * c)
    print("c * c =", c2)
    c3 = (2 * a * b)
    print("2 * a * b =", c3)
    c4 = (2 * b * c)
    print("2 * b * c =", c4)
    c5 = (2 * c * a)
    print("2 * c * a =", c5)
    x = c0 + c1 + c2 - c3 + c4 - c5
    print(c0, "+", c1, "+", c2, "-", c3, "+", c4, "-", c5, "=", x)
    print("total =", x)


print("the following formulae are \n1.(a+b)^2\n2.(a-b)^2\n3.(a+b)^3\n4.(a-b)^3\n5.(a)^3+(b)^3\n6.(a)^3+(b)^3\n7.(a+b+c)^2\n8.(a-b-c)^2")
print("enter your needed formula number ")
z = int(input())
if z<=6 :
    a = int(input("enter the value of a \n"))
    b = int(input("enter the value of b \n"))
else:
    a = int(input("enter the value of a \n"))
    b = int(input("enter the value of b \n"))
    c = int(input("enter the value of c \n"))

#print("1.(a+b)^2\n2.(a-b)^2\n3.(a+b)^3\n4.(a-b)^3\n5.(a)^3+(b)^3")

choice = z
if choice ==1:for1()
elif choice ==2:for2()
elif choice ==3:for3()
elif choice ==4:for4()
elif choice ==5:for5()
elif choice ==6:for6()
elif choice ==7:for7()
elif choice ==8:for8()
else:
